[build-system]
requires = ["sphinx-theme-builder >= 0.2.0a7"]
build-backend = "sphinx_theme_builder"

[tool.sphinx-theme-builder]
node-version = "16.13.2"
theme-name = "sphinx_book_theme"
additional-compiled-static-assets = [
  "locales/"
]

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[project]
name = "sphinx-book-theme"
description = "A clean book theme for scientific explanations and documentation with Sphinx"
dynamic = ["version"]
readme = "README.md"

requires-python = ">=3.7"
dependencies = [
  "sphinx>=4,<6",
  "pydata-sphinx-theme~=0.10.1",
  "pyyaml",
]

license = { file = "LICENSE" }
# TODO: Add email of the maintainer
maintainers = [
  { name = "Chris Holdgraf", email = "choldgraf@gmail.com" },
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Framework :: Sphinx",
  "Framework :: Sphinx :: Theme",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
code_style = [
    "pre-commit>=2.7,<2.21"
]
doc = [
    "ablog~=0.10.13",
    "ipywidgets",
    "folium",
    "numpy",
    "matplotlib",
    "numpydoc",
    "myst-nb~=0.13.2",
    "nbclient",
    "pandas",
    "plotly",
    "sphinx>=4,<7",
    "sphinx-design",
    "sphinx-examples",
    "sphinx-copybutton",
    "sphinx-tabs",
    "sphinx-togglebutton>=0.2.1",
    "sphinx-thebe>=0.1.1",
    "sphinxcontrib-bibtex~=2.2",
    "sphinxcontrib-youtube",
    "sphinxext-opengraph",
]
test = [
    "beautifulsoup4>=4.6.1,<5",
    "coverage",
    "myst-nb~=0.13.2",
    "pytest~=7.1",
    "pytest-cov>=3,<5",
    "pytest-regressions>=2.0.1,<2.5.0",
    "sphinx_thebe",
    # 8.7.0 broke the `ipython3` lexer in Sphinx so we want to avoid it
    "ipython!=8.7.0",
]

[project.entry-points]
"sphinx.html_themes" = { sphinx_book_theme = "sphinx_book_theme" }

[project.urls]
Repository = "https://github.com/executablebooks/sphinx-book-theme"
Documentation = "https://sphinx-book-theme.readthedocs.io/"
